SELECT count(*)
  FROM GV$SESSION S
  JOIN GV$SESSION BLOCKER ON BLOCKER.INST_ID = S.FINAL_BLOCKING_INSTANCE AND BLOCKER.SID = S.FINAL_BLOCKING_SESSION
 --WHERE S.FINAL_BLOCKING_SESSION_STATUS = 'VALID'
;
